# Generated by Django 3.1.4 on 2020-12-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('bookname', models.CharField(max_length=26)),
                ('bookauth', models.CharField(max_length=10)),
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookstore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookObsoInfo',
            fields=[
                ('obtime', models.DateTimeField(primary_key=True, serialize=False)),
                ('obnum', models.IntegerField()),
                ('bookinfos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookLeaseInfo',
            fields=[
                ('Letime', models.DateTimeField(primary_key=True, serialize=False)),
                ('Lenum', models.IntegerField()),
                ('Letarget', models.CharField(max_length=10)),
                ('bookinfos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookBuyInfo',
            fields=[
                ('buytime', models.DateTimeField(primary_key=True, serialize=False)),
                ('buynum', models.IntegerField()),
                ('bookinfos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.bookinfo')),
            ],
        ),
    ]
