# Generated by Django 3.1.4 on 2020-12-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0002_auto_20201231_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bookname',
            field=models.CharField(max_length=26),
        ),
    ]
