# Generated by Django 3.1.4 on 2020-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0004_remove_bookinfo_bookstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bookstore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
