# Generated by Django 3.1.4 on 2020-12-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0005_bookinfo_bookstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bookstore',
            field=models.IntegerField(default=0),
        ),
    ]
